# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./src/OurHouse
    - name: Build
      run: dotnet build --no-restore --configuration Release
      working-directory: ./src/OurHouse
    - name: Generate pages
      run: dotnet run --no-restore --configuration Release ssg OurHouse ../../web
      working-directory: ./src/OurHouse
    - name: List files to deploy
      run: |
       cd web
       ls
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.6.1
      with:
        branch: gh-pages
        folder: web/OurHouse
    - name: Restore tests dependencies
      run: dotnet restore
      working-directory: ./tests/OurHouse.Tests
    - name: Build Tests
      run: dotnet build --no-restore --configuration Release
      working-directory: ./tests/OurHouse.Tests
    - name: Ensure browsers are installed
      run: pwsh bin/Release/net8.0/playwright.ps1 install --with-deps
      working-directory: ./tests/OurHouse.Tests
    - name: Tests
      run: dotnet test --verbosity normal --configuration Release --settings gh-pages.runsettings
      working-directory: ./tests/OurHouse.Tests
