# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/OurHouse
    - name: Build
      run: dotnet build --no-restore ./src/OurHouse --configuration Release
    - name: Generate pages
      run: dotnet run --no-restore --project ./src/OurHouse --configuration Release ssg
    - name: List files to deploy
      run: |
       cd web
       ls
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.6.1
      with:
        branch: gh-pages
        folder: web
